### ISSUE TITLE
'appwrite init function' doesn't work on Windows

### ISSUE THREAD

**Issue by watzon** [appwrite/sdk-for-cli#30] opened 2022-03-15 22:31 UTC
Seems like there might be something linux specific with `appwrite init function`.  When attempting on Windows I get 
```
Error ENOENT: no such file or directory, open 'C:\...\functions\My Awesome Function\README.md'
```

Node version: v17.7.1
Appwrite CLI version: 0.15.0

Tried with both CMD and Powershell

**Comment by christyjacob4** [comment] 2022-03-15 22:42
You're right @watzon Thank you for raising this. We're using Unix specific `mkdir` in the code causing it to fail on Windows. 
As a temporary work around, please use WSL. 

We have this noted and we'll fix it soon 🙂

**Comment by anandsubbu007** [comment] 2022-05-01 07:39
any update?

**Comment by Meldiron** [comment] 2022-05-05 08:16
Addressed in PR: https://github.com/appwrite/sdk-generator/pull/406

**Comment by stnguyen90** [comment] 2022-05-21 21:48
Duplicate of https://github.com/appwrite/sdk-for-cli/issues/29

**Comment by DanielAlbertSwan** [comment] 2022-07-22 12:00
The Windows specific code is missing in current master is this intended?

**Comment by stnguyen90** [comment] 2022-07-25 19:22
> The Windows specific code is missing in current master is this intended?

Thanks for bringing this up! 🙏  The code seems to have disappeared. 🧐 We'll look into it and fix it ASAP.

**Comment by stnguyen90** [comment] 2022-07-26 04:49
@DanielAlbertSwan, we just pushed 0.18.4. How does it look now?

**Comment by DanielAlbertSwan** [comment] 2022-08-02 11:56
Yes now it is working

**Closed** 2022-08-02 16:31 UTC
Labels: bug
