### ISSUE TITLE
🐛 Bug Report:  Appwrite -v results in error

### ISSUE THREAD

**Issue by tripathi-g** [appwrite/sdk-for-cli#92] opened 2023-08-30 14:55 UTC
### 👟 Reproduction steps

npm install -g appwrite-cli

appwrite -v

### 👍 Expected behavior

install the package globally and show version

### 👎 Actual Behavior

install the package globally completed
but not able to use appwrite

appwrite -v results in error
![image](https://github.com/appwrite/sdk-for-cli/assets/55848734/e7257c8e-3398-4f42-8f83-ed50982080dd)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by e1ke** [comment] 2023-08-30 15:04
maybe related to my bug with the new sdk-for-cli 3.0.0
https://github.com/appwrite/sdk-for-cli/issues/93

**Comment by tripathi-g** [comment] 2023-08-30 15:12
> maybe related to my bug with the new sdk-for-cli 3.0.0 #93

Yes. I am facing the same issue like yours
@eldadfux  is this related to the newer version ?

**Comment by e1ke** [comment] 2023-08-31 07:26
> Yes. I am facing the same issue like yours

does it work with the prior version 2.0.2?
see my comment https://github.com/appwrite/sdk-for-cli/issues/93#issuecomment-1700505472

**Comment by istornz** [comment] 2023-08-31 11:55
Same for me too ...

**Comment by joeyouss** [comment] 2023-08-31 18:52
Hi @tripathi-g , thank you for opening the issue, we are looking into it. I will get back to you ASAP.

**Comment by stnguyen90** [comment] 2023-08-31 22:46
Closing as a duplicate of https://github.com/appwrite/sdk-for-cli/issues/93

**Closed by stnguyen90** 2023-08-31 22:46 UTC
Labels: bug

**Comment by DHsoftw** [comment] 2023-09-01 10:46
> Closing as a duplicate of #93

They're different errors, so not duplicate

**Comment by stnguyen90** [comment] 2023-09-01 18:22
@DHsoftw the error is thrown by `configureHelp()` in `assistant.js` for both.

**Comment by simoneickhoff** [comment] 2023-09-03 12:22
Having the same issue since v3.0.0. I use Node.js 18.17.1 installed via nvm.

**Comment by rodolfogoulart** [comment] 2023-09-06 21:00
Same error on Windows 11

Node.js v18.17.1
