### ISSUE TITLE
🐛 Bug Report: Fails to deploy function thru appwrite cli when variables is defined.

### ISSUE THREAD

**Issue by spontaneouscombustion** [appwrite/sdk-for-cli#111] opened 2024-02-26 08:28 UTC
### 👟 Reproduction steps

Deploy a function with variables set on appwrite.json using appwrite cli
appwrite.json
```json
{
    "projectId": "ProjectID",
    "projectName": "ProjectName",
    "functions": [
        {
            "$id": "FunctionID",
            "name": "AdminUtil",
            "runtime": "node-18.0",
            "execute": [
                "any"
            ],
            "events": [],
            "schedule": "",
            "timeout": 15,
            "enabled": true,
            "logging": true,
            "entrypoint": "src/main.js",
            "commands": "npm install",
            "ignore": [
                "node_modules",
                ".npm"
            ],
            "path": "functions/admin",
            "variables": {
              "APITOKEN": "REDACTED"
            }
        }
    ], ...
```

I thinks this has something to do with this line
https://github.com/appwrite/sdk-for-cli/blob/ead5533796ccfd5d1bbedb50e7bf65d2b0c1337f/lib/commands/deploy.js#L313C24-L313C39
using remoteVariables.length property in a statement even though remoteVariables is undefined

### 👍 Expected behavior

a successful deploy with the env variables defined/updated

### 👎 Actual Behavior

The deployment fail.
The log reports "remoteVariables is not defined"

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

cloud.appwrite.io
Runtime: Node.js 18

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-03-12 11:45
Closing as a duplicate of https://github.com/appwrite/sdk-for-cli/issues/112

**Closed by stnguyen90** 2024-03-12 11:45 UTC
Labels: bug
